fun_facts = (
    "A cloud weighs around a million tonnes. A cloud typically has a volume of around 1km3 and a density of around 1.003kg per m3 – that’s a density that’s around 0.4 per cent lower than the air surrounding it (this is how they are able to float).",
    "Giraffes are 30 times more likely to get hit by lightning than people. True, there are only five well-documented fatal lightning strikes on giraffes between 1996 and 2010. But due to the population of the species being just 140,000 during this time, it makes for about 0.003 lightning deaths per thousand giraffes each year. This is 30 times the equivalent fatality rate for humans.",
    "Identical twins don’t have the same fingerprints. You can’t blame your crimes on your twin, after all. This is because environmental factors during development in the womb (umbilical cord length, position in the womb, and the rate of finger growth) impact your fingerprint.",
    "Earth’s rotation is changing speed. It's actually slowing. This means that, on average, the length of a day increases by around 1.8 seconds per century. 600 million years ago a day lasted just 21 hours.",
    "Your brain is constantly eating itself. This process is called phagocytosis, where cells envelop and consume smaller cells or molecules to remove them from the system. Don’t worry! Phagocytosis isn't harmful, but actually helps preserve your grey matter.",
    "The largest piece of fossilised dinosaur poo discovered is over 30cm long and over two litres in volume. Believed to be a Tyrannosaurus rex turd, the fossilised dung (also named a 'coprolite') is helping scientists better understand what the dinosaur ate.",
    "The Universe's average colour is called 'Cosmic latte'. In a 2002 study, astronomers found that the light coming from galaxies averaged into a beige colour that’s close to white.",
    "Animals can experience time differently from humans. To smaller animals, the world around them moves more slowly compared to humans. Salamanders and lizards, for example, experience time more slowly than cats and dogs. This is because the perception of time depends on how quickly the brain can process incoming information.",
    "Water might not be wet. This is because most scientists define wetness as a liquid’s ability to maintain contact with a solid surface, meaning that water itself is not wet, but can make other objects wet.",
    "A chicken once lived for 18 months without a head. Mike the chicken's incredible feat was recorded back in the 1940s in the USA. He survived as his jugular vein and most of his brainstem were left mostly intact, ensuring just enough brain function remained for survival. In the majority of cases, a headless chicken dies in a matter of minutes.",
    "All the world’s bacteria stacked on top of each other would stretch for 10 billion light-years. Together, Earth's 0.001mm-long microbes could wrap around the Milky Way over 20,000 times.",
    "Wearing a tie can reduce blood flow to the brain by 7.5 per cent. A study in 2018 found that wearing a necktie can reduce the blood flow to your brain by up to 7.5 per cent, which can make you feel dizzy, nauseous, and cause headaches. They can also increase the pressure in your eyes if on too tight and are great at carrying germs.",
    "The fear of long words is called Hippopotomonstrosesquippedaliophobia. The 36-letter word was first used by the Roman poet Horace in the first century BCE to criticise those writers with an unreasonable penchant for long words. It was American poet Aimee Nezheukumatathil, possibly afraid of their own surname, who coined the term how we know it in 2000.",
    "The world’s oldest dog lived to 29.5 years old. While the median age a dog reaches tends to be about 10-15 years, one Australian cattle dog, ‘Bluey’, survived to the ripe old age of 29.5.",
    "The world’s oldest cat lived to 38 years and three days old. Creme Puff was the oldest cat to ever live.",
    "The Sun makes a sound but we can't hear it. In the form of pressure waves, the Sun does make a sound. The wavelength of the pressure waves from the Sun is measured in hundreds of miles, however, meaning they are far beyond the range of human hearing.",
    "Mount Everest isn't the tallest mountain on Earth. Mauna Kea and Mauna Loa in Hawaii, the twin volcanoes, are taller than Mount Everest due to 4.2km of their heights being submerged underwater. The twin volcanoes measure a staggering 10.2km in total, compared to Everest’s paltry 8.8km.",
    "Our solar system has a wall. The heliopause – the region of space in which solar wind isn’t hot enough to push back the wind of particles coming from distant stars – is often considered the “boundary wall” of the Solar System and interstellar space.",
    "Octopuses don’t actually have tentacles. They have eight limbs, but they're arms (for most species). Technically, when talking about cephalopods (octopuses, squids etc), scientists define tentacles as limbs with suckers at their end. Octopus arms have suckers down most of their length.",
    "Most maps of the world are wrong. On most maps, the Mercator projection – first developed in 1569 – is still used. This method is wildly inaccurate and makes Alaska appear as large as Brazil and Greenland 14 times larger than it actually is. For a map to be completely accurate, it would need to be life-size and round, not flat.",
    "NASA genuinely faked part of the Moon landing. While Neil Armstrong's first steps on the lunar surface were categorically not faked, the astronaut quarantine protocol when the astronauts arrived back on Earth was largely just one big show.",
    "Comets smell like rotten eggs. A comet smells like rotten eggs, urine, burning matches, and… almonds. Traces of hydrogen sulphide, ammonia, sulphur dioxide, and hydrogen cyanide were all found in the makeup of the comet 67P/Churyumove-Gerasimenko. Promotional postcards were even commissioned in 2016 carrying the pungent scent of a comet.",
    "Earth’s poles are moving. This magnetic reversal of the North and South Pole has happened 171 times in the past 71 million years. We’re overdue a flip. It could come soon, as the North Pole is moving at around 55 kilometres per year, an increase over the 15km per year up until 1990.",
    "You can actually die laughing. And a number of people have, typically due to intense laughter causing a heart attack or suffocation. Comedy shows should come with a warning.",
    "Chainsaws were first invented for childbirth. It was developed in Scotland in the late 18th Century to help aid and speed up the process of symphysiotomy (widening the pubic cartilage) and removal of disease-laden bone during childbirth. It wasn’t until the start of the 20th Century that we started using chainsaws for woodchopping.",
    "Ants don’t have lungs. They instead breathe through spiracles, nine or ten tiny openings, depending on the species.",
    "The T.rex likely had feathers. Scientists in China discovered Early Cretaceous period tyrannosaur skeletons that were covered in feathers. If the ancestors of the T. rex had feathers, the T. rex probably did, too.",
    "Football teams wearing red kits play better. The colour of your clothes can affect how you’re perceived by others and change how you feel. A review of football matches in the last 55 years, for example, showed that teams wearing a red kit consistently played better in home matches than teams in any other colour.",
    "Wind turbines kill between 10,000 and 100,000 birds each year in the UK. Interestingly, painting one of the blades of a wind turbine black can reduce bird deaths by 70 per cent.",
    "Snails have teeth. Between 1,000 and 12,000 teeth, to be precise. They aren’t like ours, though, so don’t be thinking about snails with ridiculous toothy grins. You’ll find the snail's tiny 'teeth' all over its file-like tongue.",
    "Sound can be minus decibels. The quietest place on Earth is Microsoft’s anechoic chamber in Redmond, WA, USA, at -20.6 decibels. These anechoic chambers are built out of heavy concrete and brick and are mounted on springs to stop vibrations from getting in through the floor.",
    "A horse normally has more than one horsepower. A study in 1993 showed that the maximum power a horse can produce is 18,000W, around 24 horsepower.",
    "Your signature could reveal personality traits. A study in 2016 purports that among men, a larger signature correlates with higher social bravado and, among women, a bigger signature correlates with narcissistic traits.",
    "One in 18 people have a third nipple. Known as polythelia, the third nipple is caused by a mutation in inactive genes.",
    "Bananas are radioactive. Due to being rich in potassium, every banana is actually slightly radioactive thanks to containing the natural isotope potassium-40. Interestingly, your body contains around 16mg of potassium-40, meaning you’re around 280 times more radioactive than a banana already. Any excess potassium-40 you gain from a banana is excreted out within a few hours.",
    "There’s no such thing as a straight line. Zoom in close enough to anything and you’ll spot irregularities. Even a laser light beam is slightly curved.",
    "Deaf people are known to use sign language in their sleep. A case study of a 71-year-old man with rapid eye movement disorder and a severe hearing impairment showed him using fluent sign language in his sleep, with researchers able to get an idea of what he was dreaming about thanks to those signs.",
    "Finland is the happiest country on Earth. According to the World Happiness Report, it has been for six years in a row. It’s not really surprising, given that Finland is the home of Santa Claus, reindeer and one sauna for every 1.59 people.",
    "Hippos can’t swim. Hippos really do have big bones, so big and dense, in fact, that they’re barely buoyant at all. They don’t swim and instead perform a slow-motion gallop on the riverbed or on the sea floor. In fact, hippos can even sleep underwater, thanks to a built-in reflex that allows them to bob up, take a breath, and sink back down without waking.",
    "The Moon looks upside down in the Southern Hemisphere. Compared to the Northern Hemisphere, anyway. This means that the ‘Man in the Moon’ is upside down in the Southern Hemisphere and looks more like a rabbit.",
    "You can yo-yo in space. In 2012, NASA astronaut Don Pettit took a yo-yo on board the International Space Station and demonstrated several tricks. It works because a yo-yo mainly relies on the laws of conservation of angular momentum to perform tricks, which, provided you keep the string taut, apply in microgravity too.",
    "Not only plants photosynthesise. Algae (which are not plants) and some other organisms – including sea slugs and pea aphids – contain chlorophyll and can also take sunlight and turn it into an energy source.",
    "You can be heavily pregnant and not realise. Cryptic pregnancies aren’t that uncommon, with 1 in 500 not recognised until at least halfway through and 1 in 2,500 not known until labour starts.",
    "Bacteria on your skin cause your itches. Specifically, bacteria known as Staphylococcus aureus can release a chemical that activates a protein in our nerves. This sends a signal from our skin to our brains, which our brain perceives as an itch.",
    "Starfish don’t have bodies. Along with other echinoderms (think sea urchins and sand dollars), their entire bodies are technically classed as heads.",
    "Somebody has been constipated for 45 days. In 2013, an unfortunate Indian woman had to undergo surgical removal of a faecal mass as large as a football.",
    "You travel 2.5 million km a day around the Sun without realising. The Earth’s orbit travels around 2.5 million kilometres with respect to the Sun’s centre, and around 19 million km with respect to the centre of the Milky Way.",
    "Fish form orderly queues in emergencies. When evacuating through narrow spaces in sketchy situations, schools of neon tetra fish queue so that they don’t collide or clog up the line. Scientists interpreted this behaviour as showing that fish can respect social rules even in emergency situations, unlike us humans.",
    "There are more bacterial cells in your body than human cells. The average human is around 56 per cent bacteria. This was discovered in a 2016 study and is far less than the earlier estimates of 90 per cent. As bacteria are so light, however, by weight, each person is over 99.7 per cent human.",
    "Most ginger cats are male. There are roughly three ginger male cats to one ginger female. This is because the ginger gene is found on the X chromosome, meaning female cats would require two copies of the gene to become ginger whilst males only need one.",
    "Your nails grow faster in hot summer. This is probably due to increased blood supply to the fingertips. It could also be because you’re less stressed while on holiday so less likely to gnaw away at ‘em.",
    "Insects can fly up to 3.25km above sea level, at least. Alpine bumblebees have been found living as high up as 3.25km above sea level and could even fly in lab conditions that replicate the air density and oxygen levels at 9km – that's just higher than Mount Everest.",
    "There’s a planet mostly made from diamond. Called 55 Cancri e, it's around twice the size of Earth and some 40 light-years away from us within the Cancer constellation.",
    "Animals can be allergic to humans. Animals can be allergic to our dead skin cells – dander. These allergic reactions can be just like ours, too, including breathing difficulties and skin irritation.",
    "Being bored is actually a 'high arousal state' physiologically. This is because when you're bored your heart rate increases.",
    "Platypuses sweat milk. This is because it doesn't have teats. Milk appears as sweat on a platypus, but it's an aquatic mammal so it doesn't actually sweat at all.",
    "LEGO bricks withstand compression better than concrete. An ordinary plastic LEGO brick is able to support the weight of 375,000 other bricks before it fails. This, theoretically, would let you build a tower nearing 3.5km in height. Scaling this up to house-size bricks, however, would cost far too much.",
    "Martial artists who smile before the start of a match are more likely to lose. This could be as a smile can convey fear or submissiveness.",
    "It's almost impossible to get too much sugar from fresh fruit. While the sugar in fruit is mostly fructose and glucose (fructose is what's converted into fat in your body), you can't get too much sugar from fresh fruit. Fresh fruit contains a lot of fibre and water which slows down your digestion and makes you feel full.",
    "You don't like the sound of your own voice because of the bones in your head. This may be because the bones in our head make our voice sound deeper.",
    "A rainbow on Venus is called a glory. Appearing as a series of coloured concentric rings, these are caused by the interference of light waves within droplets, rather than the reflection, refraction and dispersion of light that makes a rainbow.",
    "Protons look like peanuts, rugby balls, bagels, and spheres. Protons come in all different shapes and sizes, with their appearance changing based on the speed of smaller particles within them: Quarks.",
    "Mirrors facing each other don't produce infinite reflections. Each reflection will be darker than the last and eventually fade into invisibility. Mirrors absorb a fraction of the energy of the light striking them. The total number of reflections mirrors can produce? A few hundred.",
    "There might be a cure for 'evil'. Well, a cure for psychopathy, anyway. Psychologists argue that aspects of psychopathy can be 'cured' by cognitive behavioural therapy, which is said to reduce violent offences by those with the condition. Preliminary research suggests that computer-based cognitive training could help a psychopath experience empathy and regret, too.",
    "All mammals get goosebumps. When your hair stands on end, tiny muscles contract at each hair's base which distorts the skin to create goosebumps. This process is called piloerection and is present in all mammals. Hair or fur is used to trap an insulating air layer.",
    "Football players spit so much because exercise increases the amount of protein in saliva. When you exercise, the amount of protein secreted into the saliva increases. A protein mucus named MUC5B makes your saliva thicker when you're exercising which makes it more difficult to swallow so we tend to spit more. It may occur during exercise because we breathe through our mouths more. MUC5B could activate to stop our mouths from drying out, therefore.",
    "Some animals display autistic-like traits. Autistic traits in animals include a tendency toward repetitive behaviour and atypical social habits.",
    "The biggest butterfly in the world has a 31cm wingspan. It belongs to the Queen Alexandra's Birdwing butterfly, which you can find in the forests of the Oro Province, in the east of Papua New Guinea.",
    "You remember more dreams when you sleep badly. Research suggests that if you sleep badly and wake up multiple times throughout the night you will be more likely to recall the content of any dreams you had. You are also more likely to remember a dream when woken from one.",
    "You could sweat when you're anxious to alert others. One theory suggests we've evolved to sweat whilst anxious to alert the brains of other people around us so they are primed for whatever it is that's making us anxious. Brain scans have revealed that when you sniff the sweat of a panic-induced person, regions of the brain that handle emotional and social signals light up. When you're anxious your sympathetic nervous system releases hormones including adrenaline, which activates your sweat glands.",
    "A lightning bolt is five times hotter than the surface of the Sun. The charge carried by a bolt of lightning is so intense that it has a temperature of 30,000°C (54,000°F).",
    "The longest anyone has held their breath underwater is over 24.5 minutes. The world record for breath-holding underwater was achieved by Croatian Budimir Šobat on 27 March 2021, who held his breath for a total of 24 minutes and 37 seconds. On average, a human can hold their breath between 30-90 seconds.",
    "The Moon is shrinking. But only very slightly – by about 50m (164ft) in radius over the last several hundred million years. Mysterious seismic activity, known as moonquakes, could be to blame.",
    "Dogs tilt their heads when you speak to them to better pinpoint familiar words. Your dog is tilting its head when you speak to it to pinpoint where noises are coming from more quickly. This is done to listen out more accurately for familiar words such as 'walkies' and helps them to better understand the tone of your voice. If a dog doesn't tilt its head that often (as those with shorter muzzles might), it's because it relies less on sound and more on sight.",
    "If the Earth doubled in size, trees would immediately fall over. This is because surface gravity would be doubled. It would also mean dog-size and larger animals would not be able to run without breaking a leg.",
    "Mercury, not Venus, is the closest planet to Earth on average. On average, Mercury is 1.04 astronomical units (AU) away from Earth compared to the 1.14 AU average distance between Earth and Venus. One AU is equal to the average distance between the Earth and the Sun. Venus still comes closest to Earth as part of its orbit around the Sun, however.",
    "Flamingoes aren’t born pink. They actually come into the world with grey/white feathers and only develop a pinkish hue after starting a diet of brine shrimp and blue-green algae.",
    "You can smell ants. Many species of ants release strong-smelling chemicals when they’re angry, threatened or being squished. Trap-jaw ants release a chocolatey smell when annoyed, while citronella ants earn their name from the lemony odour they give off.",
    "People who eat whatever they want and stay slim have a slow metabolism, not fast. A skinny person tends to have less muscle mass than others, meaning their basal metabolic rate (BMR) is lower than those of a high muscle mass – this gives them a slow metabolism, not a fast one.",
    "Earth is 4.54 billion years old. Using radiometric dating, scientists have discovered that the Earth is 4.54 billion years old (give or take 50 million years). This makes our planet half the age of the Milky Way Galaxy (11-13 billion years old) and around a third of the age of the Universe (10-15 billion years old).",
    "Electrons might live forever. Scientists have estimated the minimum lifetime of the electron is about 6.6 × 1028 years – this is 66,000 ‘yottayears’. Since this is about 5 quintillion times the age of the Universe, even if electrons don’t live forever, they may as well do!",
    "Beavers don't actually live in dams. Technically, beavers live in a lodge that they build behind a dam, within a deep pool of water.",
    "The average dinosaur lifespan was surprisingly small. The Tyrannosaurus rex, for example, reached full size between 16-22 years old and lived up until 27-33. The largest dinosaurs such as the Brontosaurus and Diplodocus tended to live up to between 39-53 years old, maybe reaching the heights of 70.",
    "Someone left a family photo on the Moon. When Apollo 16 astronaut Charles Duke landed on the Moon in 1972, he decided to leave behind a photo of him, his two sons and his wife. The photo remains on the Moon to this day.",
    "It rains methane on Saturn’s largest moon. Titan is the only moon in our Solar System with a dense atmosphere and the only body except Earth with liquid rivers, lakes and seas fed by rainfall. This rainfall isn’t water, though; it's liquid methane.",
    "Giraffes hum to communicate with each other. It’s thought that the low-frequency humming could be a form of ‘contact call’ between individuals who have been separated from their herd, helping them to find each other in the dark. Some researchers think they sleep talk too.",
    "Glass sponges can live for 15,000 years. This makes them one of the longest-living organisms on Earth. The immortal jellyfish, however, could theoretically live forever (but scientists aren’t sure)",
    "You have a 50 per cent chance of sharing a birthday with a friend. In any group of 23 people, two people will share a birthday, according to the maths. To find the probability of everyone in the group having a unique birthday, multiply all 23 probabilities together, giving 0.493. So the probability of a shared birthday is 1 - 0.493 = 0.507, or 50.7 per cent.",
    "Murder rates rise in summer. Ever feel angry or in a bad mood when the weather is hot? Well, you’re not alone. Violent crime goes up in hotter weather, and in the US, murder rates reportedly rise by 2.7 per cent over the summer.",
    "'New car smell' is a mix of over 200 chemicals. These include the sickly-sweet, toxic hydrocarbons benzene and toluene.",
    "‘Sea level’ isn’t actually level. As the strength of the force generated by the Earth’s spin is strongest at the equator, the average sea level bulges outward there, putting it further from the centre of the Earth than at the poles. Differences in the strength of the Earth’s gravity at different points also cause variation.",
    "You inhale 50 potentially harmful bacteria every time you breathe. Thankfully, your immune system is working hard all the time, so virtually all of these are promptly destroyed without you feeling a thing. Phew.",
    "You can see stars as they were 4,000 years ago with the naked eye. Without a telescope, all the stars we can see lie within about 4,000 light-years of us. That means at most you’re seeing stars as they were 4,000 years ago, around when the pyramids were being built in Egypt.",
    "Plants came before seeds. According to the fossil record, early plants resembled moss and reproduced with single-celled spores. Multicellular seeds didn’t evolve for another 150 million years.",
    "Our dead cells are eaten by other cells in our body. Don’t worry; it’s meant to happen. When cells inside your body die, they’re scavenged by phagocytes – white blood cells whose job it is to digest other cells.",
    "Smells can pass through liquid. Please don’t try smelling underwater (your nose will not appreciate it), but smell does protrude through liquid.",
    "Bats aren’t blind. Despite the famous idiom, bats can indeed see, but they still use their even more famous echolocation to find prey.",
    "Pine trees can tell if it's about to rain. Next time you see a pine cone, take a close look. If it’s closed, that’s because the air is humid, which can indicate rain is on its way.",
    "You can’t fold a piece of A4 paper more than eight times. As the number of layers doubles each time, the paper rapidly gets too thick and too small to fold. The current world paper-folding record belongs to California high school student Britney Gallivan, who in 2002 managed to fold a 1.2km-long piece of tissue paper 12 times.",
    "Laughing came before language. How do we know? Some researchers tickled baby apes, which, beyond being adorable, showed that they share the same structure as ours and likely arose in our common ancestors millions of years ago. Language came about much later.",
    "Your brain burns 400-500 calories a day. That’s about a fifth of your total energy requirements. Most of this is concerned with the largely automatic process of controlling your muscles and processing sensory input, although some studies show solving tricky problems increases your brain's metabolic requirements too."
)

jokes = (
    "I just got my doctor's test results and I'm really upset about it. Turns out, I'm not gonna be a doctor.",
    "My grief counselor died. He was so good, I don't even care.",
    "Today, I asked my phone, \"Siri, why am I still single?\" and it activated the front camera.",
    "A man wakes from a coma. His wife changes out of her black clothes and, irritated, remarks, \"I really cannot depend on you in anything, can I!\"",
    "As I get older, I remember all the people I lost along the way. Maybe my budding career as a tour guide was not the right choice.",
    "I was digging in our garden and found a chest full of gold coins. I wanted to run straight home to tell my wife about it. Then, I remembered why I was digging in our garden.",
    "The doctor gave me some cream for my skin rash. He said I was a sight for psoriasis.",
    "Don't challenge Death to a pillow fight. Unless you're prepared for the reaper cushions.",
    "I don't have a carbon footprint. I just drive everywhere.",
    "Even people who are good for nothing have the capacity to bring a smile to your face, like when you push them down the stairs.",
    "A man walks into an enchanted forest and tries to cut down a talking tree. \"You can't cut me down,\" the tree exclaims, \"I'm a talking tree!\" The man responds, \"You may be a talking tree, but you will dialogue.\"",
    "My mom died when we couldn't remember her blood type. As she died, she kept telling us to \"be positive,\" but it's hard without her.",
    "What does my dad have in common with Nemo? They both can't be found.",
    "I visited my new friend in his apartment. He told me to make myself at home. So I threw him out. I hate having visitors.",
    "When my Uncle Frank died, he wanted his cremations to be buried in his favorite beer mug. His last wish was to be Frank in Stein.",
    "Do you know the phrase \"One man's trash is another man's treasure\"? It's a wonderful saying but a horrible way to find out that you were adopted.",
    "My husband left a note on the fridge that said, \"This isn't working.\" I'm not sure what he's talking about. I opened the fridge door, and it's working fine!",
    "Why did the man miss the funeral? He wasn't a mourning person.",
    "It's important to establish a good vocabulary. If I had known the difference between the words \"antidote\" and \"anecdote,\" one of my best friends would still be alive.",
    "Want to know how you make any salad into a caesar salad? Stab it twenty-three times.",
    "When does a joke become a dad joke? When it leaves you and never comes back.",
    "Give a man a match, and he'll be warm for a few hours. Set him on fire, and he will be warm for the rest of his life.",
    "My wife is mad that I have no sense of direction. So I packed up my stuff and right.",
    "When I see the names of lovers engraved on a tree, I don't find it cute or romantic. I find it weird how many people take knives with them on outings.",
    "A priest asks the convicted murderer in the electric chair, \"Do you have any last requests?\" \"Yes,\" replies the murderer. \"Can you please hold my hand?\"",
    "I just read that someone in New York gets stabbed every 52 seconds. Poor guy.",
    "The doctor gave me one year to live, so I shot him with my gun. The judge gave me 15 years. Problem solved.",
    "You know you're not liked when you get handed the camera every time they take a group photo.",
    "Where did Joe go after getting lost in a minefield? Everywhere.",
    "What's red and bad for your teeth? A brick.",
    "My grandfather said my generation relies too much on the latest technology. So, I unplugged his life support.",
    "My parents raised me as an only child, which really pissed off my sister.",
    "What did the Titanic say as it sank? I'm nominating all passengers for the Ice Bucket Challenge!",
    "Why did Mozart kill all of his chickens? When he asked them who the best composer was, they all replied, \"Bach, Bach, Bach.\"",
    "How many emo kids does it take to screw in a lightbulb? None, they all sit in the dark and cry.",
    "I have a stepladder because my real ladder left when I was five.",
    "They laughed at my crayon drawing. I laughed at their chalk outline.",
    "My husband and I have reached the difficult decision that we do not want children. If anybody does, please just send me your contact details, and we can drop them off tomorrow.",
    "I have many jokes about unemployed people—sadly, none of them work.",
    "The most corrupt CEOs are the ones who run pretzel companies. They're always so twisted.",
    "I was reading a great book about an immortal cat the other day. It was impossible to put down.",
    "To teach kids about democracy, I let them vote on dinner. They picked tacos. Then, I made pizza because they don't live in a swing state.",
    "You're not completely useless. You can always be used as a bad example.",
    "I threw a boomerang a few years ago. I now live in constant fear.",
    "What's the difference between a hipster and a football player? A football player showers.",
    "I made a website for orphans. It doesn't have a home page.",
    "The other day, my girlfriend asked me to pass her lipstick, but I accidentally passed her a glue stick. She still isn't talking to me.",
    "Why can't Michael Jackson go within 500 meters of a school? Because he's dead.",
    "\"I'm sorry\" and \"I apologize\" mean the same thing. Except at a funeral.",
    "A major new study recently found that humans eat more bananas than monkeys. But I can't remember the last time I ate a monkey.",
    "Never break someone's heart; they only have one. Break their bones instead. They have 206 of them.",
    "What's the difference between a Lamborghini and a dead body? I don't have a Lamborghini in my garage.",
    "When ordering food at a new restaurant, my wife asked the waiter what they do to prepare their chicken. \"Nothing special,\" he explained. \"We just tell them they're going to die.\"",
    "What is the difference between Iron Man and Iron Woman? One is a superhero, and the other is a simple command.",
    "I'll never forget my Grandfather's last words to me just before he died. \"Are you still holding the ladder?\"",
    "Sorry, what's the quickest way to get to the hospital? It's easy: just stand in the middle of a busy road.",
    "Why don't cannibals eat clowns? Because they taste funny.",
    "What's the hardest part of a vegetable to eat? The wheelchair.",
    "What's the difference between jelly and jam? You can't jelly a clown into the tiny car.",
    "My grandma has the heart of a lion and a lifetime ban from the zoo.",
    "You don't need a parachute to go skydiving. You need a parachute to go skydiving twice.",
    "What did the woman with no hands get for Christmas? No idea. She hasn't opened her present yet.",
    "\"I work with animals,\" the guy says to his Tinder date. \"That's so sweet,\" she replies. \"I like a man who loves animals. Where do you work?\" \"I'm a butcher,\" he says.",
    "What's the difference between a baby and a sweet potato? About 140 calories.",
    "What do you call inexpensive circumcision? A rip-off.",
    "Today was the worst day of my life. My ex got hit by a school bus, and I lost my job as a bus driver.",
    "Why was the leper hockey game canceled? It was because of a face-off in the corner.",
    "They say the surest way to a man's heart is through the stomach. But I find going through the ribcage a lot easier.",
    "What's the last thing to go through a fly's head as it hits the windshield of a car going 80 mph? Its butt.",
    "What's the special dish in a restaurant for cannibals? Heads, shoulders, knees and toes",
    "Why are friends a lot like snow? If you pee on them, they disappear.",
    "What do you call a dog with no legs? Doesn't matter what you call him, he won't come anyway.",
    "An apple a day keeps the doctor away. Or at least it does if you throw it hard enough.",
    "Why is it that if you donate a kidney, people love you. But if you donate five kidneys, they call the police.",
    "My senior relatives liked to tease me at weddings, saying things like, \"You'll be next!\" They stopped once I started doing the same to them at funerals.",
    "Happy 60th birthday. At last, you can live undisturbed by life insurance agents!",
    "Imagine if you walked into a bar and there was a long line of people waiting to hit you. That's the punch line.",
    "Dark humor is like food. Not everyone gets it.",
    "The cemetery is so crowded. People are just dying to get in.",
    "I was drinking a martini when the waitress screamed, \"Does anyone know CPR?\" I yelled, \"I know the entire alphabet,\" and we all laughed and laughed—well, except one person.",
    "I childproofed my house. Somehow they still got in!",
    "I know a fish that can breakdance! Only for 20 seconds, though, and only once.",
    "Why don't skeletons ever go trick-or-treating? Because they have no body to go with.",
    "Cremation. My final hope for a smokin' hot body!",
    "Today, on a drive, I decided to go visit my childhood home. I asked the people living there if I could come inside because I was feeling nostalgic, but they refused and slammed the door in my face. My parents are the worst.",
    "I've heard that three out of five people suffer from a chronic disease. Does that mean two out of five people enjoy it?",
    "My favorite Disney movie is The Hunchback of Notre Dame. I love a hero with a twisted back story.",
    "My girlfriend wanted a marriage just like a fairy tale. Fair enough. I gave her a loaf of bread and left her in the forest.",
    "You know, I used to be addicted to the hokey pokey. Fortunately, I turned myself around.",
    "Did you hear about the elderly man who fell into a well? No? Yeah, apparently he couldn't see that well.",
    "My boss told me to have a good day. So I went home.",
    "I got a job at a library, but it only lasted 15 minutes. Turns out, books about women's rights shouldn't go in the Sci-Fi/Fantasy section.",
    "I started crying when Dad was cutting onions. Onions was such a good dog.",
    "My daughter asked me how stars die. \"Usually an overdose,\" I told her.",
    "Why did the lion go to therapy? Because he found out his wife was a cheetah!",
    "What did Kermit the Frog say at his puppeteer's funeral? Not a word.",
    "Why is there air conditioning in hospitals? To keep the vegetables cool and fresh.",
    "The guy who stole my diary just died. My thoughts are with his family.",
    "I told my therapist that my wife and I have no chemistry. He didn't have a reaction.",
    "I was shocked when I found out my toaster was not waterproof.",
    "I told my wife that she should embrace her mistakes. So, she gave me a hug.",
    "The other day, I came across my wife's dating profile. I'm so angry about her lies. She is not \"fun to be around.\"",
    "The best way to use a stress ball is to throw it at the last person who upset you.",
    "We always treat our father like a god. We ignore him until we need something.",
    "When it's time for me to die, I hope it's during a stand-up comedy routine. That way, everyone can say I killed it.",
    "Why did the zombies get divorced? Their marriage was dead.",
    "What do you call headphones that walk out on their children? Deadbeats.",
    "I asked my wife to clean the oven. I probably should have turned it off first.",
    "I can't believe I got fired from the calendar factory. All I did was take a day off.",
    "When I was a kid, I was afraid of the dark. Now that I'm grown up, the electricity bill made me afraid of the light.",
    "I thought opening a door for a lady was good manners, but she just screamed and flew out of the plane.",
    "I bought my blind friend a cheese grater for his birthday. He later told me it was the most violent book he'd ever read.",
    "My girlfriend dumped me, so I stole her wheelchair. Guess who came crawling back?",
    "Welcome to Plastic Surgery Anonymous. Nice to meet so many new faces.",
    "My wife is mad that I ruined our anniversary. I'm not sure how; I didn't even know it was today.",
    "I tried to warn my son about playing Russian roulette. It went in one ear and out the other.",
    "I took my family skydiving. I should have given them parachutes.",
    "If someone burns to death, do they get a discount on the cremation?",
    "My therapist said time heals all wounds, so I stabbed her.",
    "My husband told me to do whatever makes him happy. I'm going to miss him.",
    "If you think I would joke about Alzheimer's, forget it.",
    "My wife told me she wants another baby. I told her, \"That's a relief; I don't really like this one anyway.",
    "I hope death is a woman. That way, it will never look at me twice.",
    "I have a joke about trickle-down economics; however, 99% of you will never get it.",
    "My husband is driving me to drink. I guess it's better than taking me for a walk.",
    "They say that life is like a box of chocolates. It's mostly filled with nuts, though.",
    "The other day, I asked the librarian if the library had any books on paranoia. She whispered, \"They're right behind you.\"",
    "I have a friend who's addicted to brake fluid. He says he can stop anytime.",
    "My family is like a software update. Every time I see them, I think, \"not now.\"",
    "Last year, my wife ran off with my best friend. I still miss him.",
    "What is yellow and can't swim? A dead goldfish.",
    "How are marriages like algebra? Because when you look at your X, you can't help but wonder Y.",
    "I'll never forget my dad's last words, \"Erase my search history, son.\"",
    "Stop elephant poaching. Everyone knows the best way to eat an elephant is grilled.",
    "I'd like to have kids one day. I don't think I could stand them any longer than that, though.",
    "I don't go to vampire weddings. They usually suck.",
    "So, my marriage counselor asked if it was true that I generally wake up grumpy in the morning. I said, \"Nah, most of the time, I just let him sleep.\"",
    "To err is human. To blame it on someone else shows management potential.",
    "I recently won $3 million on the lottery and decided to donate a quarter of it to charity. I now have $2,999,999.75.",
    "A man just stole my milk, butter and cheese. How dairy.",
    "Did you hear about the guy who got his left side chopped off? He's all right now.",
    "What's the difference between love and marriage? Love is blind. Marriage is eye-opening.",
    "I'm famous for my motivational skills at work. Everyone says they have to work twice as hard when I'm on the team.",
    "When a kid burned down his house, his father watched, put an arm around his wife, and said, \"That's arson.\"",
    "What did the cow say to the leather chair? \"Hi, Mom!\"",
    "Good moms let you lick the beaters when they're making a cake. Great moms turn them off first.",
    "I once asked the Grim Reaper for a favor. He said, \"Sure, but it'll cost you an arm and a leg.\"",
    "What's worse than biting into an apple and discovering a worm? Biting into an apple and discovering half a worm.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "I wasn't close to my dad when he died. Which is lucky because he stepped on a landmine.",
    "So, why did you leave your last job? Well, the company relocated and didn't tell me where.",
    "Did you hear about the couple of bed bugs? They got married in the spring.",
    "Wife: \"I'm pregnant.\" Husband: \"Hi pregnant, I'm dad.\" Wife: \"No, you're not.\"",
    "How are husbands like wine? They take years and years to fully mature.",
    "Why is being married worse than having to go to work? Because, at least with work, there's a chance you'll get a new boss."
)
